global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'shipment-service:8082'
          - 'fleet-service:8083'
          - 'ai-assistant-service:8084'
          - 'analytics-service:8086'
